# Generated by Django 5.1.1 on 2024-11-19 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlmacen', models.CharField(max_length=50)),
                ('estadoAlmacen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlmacenGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreAlmacen', models.CharField(default='Almacén Global', max_length=50)),
                ('estadoAlmacen', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObra', models.CharField(max_length=50)),
                ('ubicacionObra', models.CharField(max_length=100)),
                ('estadoObra', models.BooleanField(default=True)),
                ('fecha_creacion_obra', models.DateField(auto_now_add=True)),
                ('fecha_cierre_obra', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRol', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoEquipo', models.CharField(max_length=50, unique=True)),
                ('nombreEquipo', models.CharField(max_length=50)),
                ('marcaEquipo', models.CharField(max_length=50)),
                ('modeloEquipo', models.CharField(max_length=50)),
                ('estadoEquipo', models.BooleanField(default=True)),
                ('estadoDisponibilidad', models.CharField(max_length=20)),
                ('vidaUtilEquipo', models.CharField(max_length=20)),
                ('fechaAdquiscion', models.DateField()),
                ('fechaFabricacion', models.DateField(blank=True, null=True)),
                ('horasUso', models.FloatField(default=0)),
                ('edadEquipo', models.CharField(max_length=20)),
                ('imagenEquipos_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cantMantPreventivos', models.PositiveIntegerField(default=0)),
                ('cantMantCorrectivos', models.PositiveIntegerField(default=0)),
                ('numFallasReportdas', models.PositiveIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.almacenes')),
                ('almacen_global', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.almacenglobal')),
            ],
        ),
        migrations.CreateModel(
            name='FallasEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_falla', models.DateField()),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('reportada', 'Reportada'), ('resuelta', 'Resuelta')], max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallas', to='users.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('cantMantPre', models.PositiveIntegerField(default=0)),
                ('cantMantCor', models.PositiveIntegerField(default=0)),
                ('estadoMantenimiento', models.BooleanField(default=True)),
                ('detalleMantenimiento', models.TextField()),
                ('responsable', models.CharField(max_length=100)),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo')], max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.equipos')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialTraspasosEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_traspaso', models.DateTimeField(auto_now_add=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_destino', to='users.almacenes')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_origen', to='users.almacenes')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.equipos')),
                ('obra_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_destino', to='users.obras')),
                ('obra_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_origen', to='users.obras')),
            ],
        ),
        migrations.AddField(
            model_name='almacenes',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.obras'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('ci', models.CharField(max_length=50, unique=True)),
                ('departamento', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('obra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.obras')),
            ],
        ),
        migrations.CreateModel(
            name='UsoSolicitudesEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoSolicitud', models.CharField(max_length=50)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_retorno_estimada', models.DateField()),
                ('fecha_retorno_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_uso', models.DateField()),
                ('descripcion_uso', models.TextField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.equipos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='RolPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.permisos')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles')),
            ],
            options={
                'unique_together': {('rol', 'permiso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.roles')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuarios')),
            ],
            options={
                'unique_together': {('usuario', 'rol')},
            },
        ),
    ]
