# Generated by Django 5.1.1 on 2024-11-20 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_equipos_almacen_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='edadEquipo',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='estadoDisponibilidad',
            field=models.CharField(default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fechaFabricacion',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipos',
            name='vidaUtilEquipo',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
