# Generated by Django 5.1.1 on 2024-10-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_equipos_imagenequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='imagen',
            field=models.FileField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarios',
            name='imagen_url',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
