# Generated by Django 5.1.1 on 2024-11-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_equipos_edadequipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.almacenes'),
        ),
    ]
