# Generated by Django 5.1.1 on 2024-10-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usuarios_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombreUsuario',
            field=models.CharField(max_length=50),
        ),
    ]
