# Generated by Django 5.1.1 on 2024-10-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usuarios_apellido_alter_usuarios_nombreusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimientos',
            name='detalleMantenimiento',
        ),
        migrations.AddField(
            model_name='mantenimientos',
            name='estadoMantenimiento',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mantenimientos',
            name='tipoMantenimiento',
            field=models.CharField(max_length=100),
        ),
    ]
