# Generated by Django 5.1.1 on 2024-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_mantenimientos_cantmantcor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usosolicitudesequipos',
            name='descripcion_uso',
        ),
        migrations.RemoveField(
            model_name='usosolicitudesequipos',
            name='motivo',
        ),
        migrations.AddField(
            model_name='usosolicitudesequipos',
            name='descripcion_falla',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usosolicitudesequipos',
            name='motivo_uso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='FallasEquipos',
        ),
    ]
