# Generated by Django 5.1.1 on 2024-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_mantenimientos_detallemantenimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimientos',
            name='detalleMantenimiento',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
