# Generated by Django 5.1.1 on 2024-11-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usosolicitudesequipos_descripcion_uso_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usosolicitudesequipos',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Uso de Solicitud de Equipo', 'verbose_name_plural': 'Usos de Solicitudes de Equipos'},
        ),
        migrations.AddField(
            model_name='usosolicitudesequipos',
            name='cantidad_fallas_solicitud',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usosolicitudesequipos',
            name='horas_uso_solicitud',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
