# Generated by Django 5.1.1 on 2024-11-21 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usosolicitudesequipos_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usosolicitudesequipos',
            options={},
        ),
        migrations.AlterField(
            model_name='usosolicitudesequipos',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('en uso', 'En Uso')], max_length=20),
        ),
    ]
