# Generated by Django 5.1.1 on 2024-10-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mantenimientos_detallemantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='imagenEquipos',
            field=models.FileField(default=1, upload_to='imagenes/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipos',
            name='imagenEquipos_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
