# Generated by Django 5.1.1 on 2024-10-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_obras_fecha_creacion_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obras',
            name='fecha_cierre_obra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
