# Generated by Django 5.1.1 on 2024-10-20 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_obras_fecha_creacion_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacenes',
            name='almacen_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='almacenes',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.obras'),
        ),
        migrations.CreateModel(
            name='HistorialTraspasosEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('almacen_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_destino', to='users.almacenes')),
                ('almacen_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacen_origen', to='users.almacenes')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.equipos')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.obras')),
            ],
        ),
    ]
