# Generated by Django 5.1.1 on 2024-10-21 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_almacenes_almacen_global_alter_almacenes_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='obra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.obras'),
        ),
    ]
