# Generated by Django 5.1.1 on 2024-10-21 02:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usuarios_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='departamento',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
